"""Initial migration after reset

Revision ID: 6ec7d46811ba
Revises: 
Create Date: 2024-04-14 10:51:25.300668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec7d46811ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_token',
                    sa.Column('token', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('token')
                    )
    op.create_table('kudos',
                    sa.Column('path', sa.String(length=80), nullable=False),
                    sa.Column('kudos', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=80), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.PrimaryKeyConstraint('path')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kudos')
    op.drop_table('app_token')
    # ### end Alembic commands ###
