"""initial migration

Revision ID: 700ad8de064b
Revises: 
Create Date: 2024-04-11 11:15:14.560192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700ad8de064b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kudos',
    sa.Column('path', sa.String(length=80), nullable=False),
    sa.Column('kudos', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kudos')
    # ### end Alembic commands ###
